/**
 * Copyright 2009-2011 École de technologie supérieure,
 * Communication Research Centre Canada,
 * Inocybe Technologies Inc. and 6837247 CANADA Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * 
 */

package com.greenstarnetwork.services.networkmanager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-12-20T15:00:52.997-05:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "INetworkManagerService", 
                  wsdlLocation = "file:/home/inocult/Projects/gsn-devel/services-client/src/main/resources/wsdl/INetworkManager.wsdl",
                  targetNamespace = "http://networkmanager.services.greenstarnetwork.com/") 
public class INetworkManagerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://networkmanager.services.greenstarnetwork.com/", "INetworkManagerService");
    public final static QName INetworkManagerPort = new QName("http://networkmanager.services.greenstarnetwork.com/", "INetworkManagerPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/inocult/Projects/gsn-devel/services-client/src/main/resources/wsdl/INetworkManager.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(INetworkManagerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/inocult/Projects/gsn-devel/services-client/src/main/resources/wsdl/INetworkManager.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public INetworkManagerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public INetworkManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public INetworkManagerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns INetworkManager
     */
    @WebEndpoint(name = "INetworkManagerPort")
    public INetworkManager getINetworkManagerPort() {
        return super.getPort(INetworkManagerPort, INetworkManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns INetworkManager
     */
    @WebEndpoint(name = "INetworkManagerPort")
    public INetworkManager getINetworkManagerPort(WebServiceFeature... features) {
        return super.getPort(INetworkManagerPort, INetworkManager.class, features);
    }

}
