/**
 * Copyright 2009-2011 École de technologie supérieure,
 * Communication Research Centre Canada,
 * Inocybe Technologies Inc. and 6837247 CANADA Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.greenstarnetwork.services.networkmanager;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-12-20T15:00:52.883-05:00
 * Generated source version: 2.4.0
 * 
 */

@WebFault(name = "NetworkManagerException", targetNamespace = "http://networkmanager.services.greenstarnetwork.com/")
public class NetworkManagerException_Exception extends Exception {
    public static final long serialVersionUID = 20111220150052L;
    
    private com.greenstarnetwork.services.networkmanager.NetworkManagerException networkManagerException;

    public NetworkManagerException_Exception() {
        super();
    }
    
    public NetworkManagerException_Exception(String message) {
        super(message);
    }
    
    public NetworkManagerException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NetworkManagerException_Exception(String message, com.greenstarnetwork.services.networkmanager.NetworkManagerException networkManagerException) {
        super(message);
        this.networkManagerException = networkManagerException;
    }

    public NetworkManagerException_Exception(String message, com.greenstarnetwork.services.networkmanager.NetworkManagerException networkManagerException, Throwable cause) {
        super(message, cause);
        this.networkManagerException = networkManagerException;
    }

    public com.greenstarnetwork.services.networkmanager.NetworkManagerException getFaultInfo() {
        return this.networkManagerException;
    }
}
