/**
 * Copyright 2009-2011 École de technologie supérieure,
 * Communication Research Centre Canada,
 * Inocybe Technologies Inc. and 6837247 CANADA Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.greenstarnetwork.services.facilitymanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-12-19T09:20:03.460-05:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", name = "IFacilityManagerPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IFacilityManagerPortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "turnOnResource", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.TurnOnResource")
    @WebMethod
    @ResponseWrapper(localName = "turnOnResourceResponse", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.TurnOnResourceResponse")
    public java.lang.String turnOnResource(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws FacilityManagerException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listAllClimates", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.ListAllClimates")
    @WebMethod
    @ResponseWrapper(localName = "listAllClimatesResponse", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.ListAllClimatesResponse")
    public java.util.List<java.lang.String> listAllClimates() throws FacilityManagerException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getArchiveDataByRangDate", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.GetArchiveDataByRangDate")
    @WebMethod
    @ResponseWrapper(localName = "getArchiveDataByRangDateResponse", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.GetArchiveDataByRangDateResponse")
    public java.lang.String getArchiveDataByRangDate(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "refreshResource", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.RefreshResource")
    @WebMethod
    @ResponseWrapper(localName = "refreshResourceResponse", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.RefreshResourceResponse")
    public java.lang.String refreshResource(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws FacilityManagerException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getResourceModel", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.GetResourceModel")
    @WebMethod
    @ResponseWrapper(localName = "getResourceModelResponse", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.GetResourceModelResponse")
    public java.lang.String getResourceModel(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @RequestWrapper(localName = "setThreshold", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.SetThreshold")
    @WebMethod
    @ResponseWrapper(localName = "setThresholdResponse", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.SetThresholdResponse")
    public void setThreshold(
        @WebParam(name = "arg0", targetNamespace = "")
        com.greenstarnetwork.services.facilitymanager.OperationalSpecs arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listAllPowerSources", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.ListAllPowerSources")
    @WebMethod
    @ResponseWrapper(localName = "listAllPowerSourcesResponse", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.ListAllPowerSourcesResponse")
    public java.util.List<java.lang.String> listAllPowerSources() throws FacilityManagerException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listAllPDUs", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.ListAllPDUs")
    @WebMethod
    @ResponseWrapper(localName = "listAllPDUsResponse", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.ListAllPDUsResponse")
    public java.util.List<java.lang.String> listAllPDUs() throws FacilityManagerException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "executeAction", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.ExecuteAction")
    @WebMethod
    @ResponseWrapper(localName = "executeActionResponse", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.ExecuteActionResponse")
    public java.lang.String executeAction(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws FacilityManagerException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listAllFacilities", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.ListAllFacilities")
    @WebMethod
    @ResponseWrapper(localName = "listAllFacilitiesResponse", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.ListAllFacilitiesResponse")
    public java.util.List<java.lang.String> listAllFacilities() throws FacilityManagerException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registerController", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.RegisterController")
    @WebMethod
    @ResponseWrapper(localName = "registerControllerResponse", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.RegisterControllerResponse")
    public boolean registerController(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "calculateOpHour", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.CalculateOpHour")
    @WebMethod
    @ResponseWrapper(localName = "calculateOpHourResponse", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.CalculateOpHourResponse")
    public java.lang.String calculateOpHour(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws FacilityManagerException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "turnOffResource", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.TurnOffResource")
    @WebMethod
    @ResponseWrapper(localName = "turnOffResourceResponse", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.TurnOffResourceResponse")
    public java.lang.String turnOffResource(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws FacilityManagerException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getResourceModel1", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.GetResourceModel1")
    @WebMethod
    @ResponseWrapper(localName = "getResourceModel1Response", targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.facilitymanager.GetResourceModel1Response")
    public java.lang.String getResourceModel1(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
