/**
 * Copyright 2009-2011 École de technologie supérieure,
 * Communication Research Centre Canada,
 * Inocybe Technologies Inc. and 6837247 CANADA Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.greenstarnetwork.services.cloudmanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-12-20T09:14:40.046-05:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", name = "ICloudManagerService")
@XmlSeeAlso({ObjectFactory.class})
public interface ICloudManagerService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "executeAction", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.ExecuteAction")
    @WebMethod
    @ResponseWrapper(localName = "executeActionResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.ExecuteActionResponse")
    public java.lang.String executeAction(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createInstanceInHost", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.CreateInstanceInHost")
    @WebMethod
    @ResponseWrapper(localName = "createInstanceInHostResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.CreateInstanceInHostResponse")
    public java.lang.String createInstanceInHost(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createInstance", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.CreateInstance")
    @WebMethod
    @ResponseWrapper(localName = "createInstanceResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.CreateInstanceResponse")
    public java.lang.String createInstance(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "stopInstance", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.StopInstance")
    @WebMethod
    @ResponseWrapper(localName = "stopInstanceResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.StopInstanceResponse")
    public java.lang.String stopInstance(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "rebootInstance", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.RebootInstance")
    @WebMethod
    @ResponseWrapper(localName = "rebootInstanceResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.RebootInstanceResponse")
    public java.lang.String rebootInstance(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @RequestWrapper(localName = "addDomain", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.AddDomain")
    @WebMethod
    @ResponseWrapper(localName = "addDomainResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.AddDomainResponse")
    public void addDomain(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setInstanceIPAddress", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.SetInstanceIPAddress")
    @WebMethod
    @ResponseWrapper(localName = "setInstanceIPAddressResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.SetInstanceIPAddressResponse")
    public java.lang.String setInstanceIPAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @RequestWrapper(localName = "removeDomain", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.RemoveDomain")
    @WebMethod
    @ResponseWrapper(localName = "removeDomainResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.RemoveDomainResponse")
    public void removeDomain(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "destroyInstance", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.DestroyInstance")
    @WebMethod
    @ResponseWrapper(localName = "destroyInstanceResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.DestroyInstanceResponse")
    public java.lang.String destroyInstance(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "hostQuery", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.HostQuery")
    @WebMethod
    @ResponseWrapper(localName = "hostQueryResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.HostQueryResponse")
    public java.util.List<java.lang.String> hostQuery(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "shutdownInstance", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.ShutdownInstance")
    @WebMethod
    @ResponseWrapper(localName = "shutdownInstanceResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.ShutdownInstanceResponse")
    public java.lang.String shutdownInstance(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "startInstance", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.StartInstance")
    @WebMethod
    @ResponseWrapper(localName = "startInstanceResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.StartInstanceResponse")
    public java.lang.String startInstance(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @RequestWrapper(localName = "initCloudManager", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.InitCloudManager")
    @WebMethod
    @ResponseWrapper(localName = "initCloudManagerResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.InitCloudManagerResponse")
    public void initCloudManager();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "describeHost", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.DescribeHost")
    @WebMethod
    @ResponseWrapper(localName = "describeHostResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.DescribeHostResponse")
    public java.lang.String describeHost(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "initDomains", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.InitDomains")
    @WebMethod
    @ResponseWrapper(localName = "initDomainsResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.InitDomainsResponse")
    public void initDomains();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "migrateInstance", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.MigrateInstance")
    @WebMethod
    @ResponseWrapper(localName = "migrateInstanceResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.MigrateInstanceResponse")
    public java.lang.String migrateInstance(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "describeHosts", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.DescribeHosts")
    @WebMethod
    @ResponseWrapper(localName = "describeHostsResponse", targetNamespace = "http://cloudmanager.services.greenstarnetwork.com/", className = "com.greenstarnetwork.services.cloudmanager.DescribeHostsResponse")
    public java.util.List<java.lang.String> describeHosts();
}
