/**
 * Copyright 2009-2011 École de technologie supérieure,
 * Communication Research Centre Canada,
 * Inocybe Technologies Inc. and 6837247 CANADA Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * 
 */

package com.greenstarnetwork.services.facilitymanager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-12-20T09:14:39.300-05:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "IFacilityManager", 
                  wsdlLocation = "file:/home/inocult/Projects/gsn-devel/controller/src/main/resources/wsdl/IFacilityManager.wsdl",
                  targetNamespace = "http://facilitymanager.services.greenstarnetwork.com/") 
public class IFacilityManager extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://facilitymanager.services.greenstarnetwork.com/", "IFacilityManager");
    public final static QName IFacilityManagerPort = new QName("http://facilitymanager.services.greenstarnetwork.com/", "IFacilityManagerPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/inocult/Projects/gsn-devel/controller/src/main/resources/wsdl/IFacilityManager.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IFacilityManager.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/inocult/Projects/gsn-devel/controller/src/main/resources/wsdl/IFacilityManager.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IFacilityManager(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IFacilityManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IFacilityManager() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns IFacilityManagerPortType
     */
    @WebEndpoint(name = "IFacilityManagerPort")
    public IFacilityManagerPortType getIFacilityManagerPort() {
        return super.getPort(IFacilityManagerPort, IFacilityManagerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFacilityManagerPortType
     */
    @WebEndpoint(name = "IFacilityManagerPort")
    public IFacilityManagerPortType getIFacilityManagerPort(WebServiceFeature... features) {
        return super.getPort(IFacilityManagerPort, IFacilityManagerPortType.class, features);
    }

}
